import ContractsTable from '@/components/ContractsTable'
import { NavBar } from '@/components/NavBar'
import { useGetContractsQuery } from '@/features/contracts/api'
import { setContracts } from '@/features/contracts/slice'
import { useAppDispatch } from '@/hooks'
import { font } from '@/utils/font'
import { Head } from 'next/document'
import React, { useEffect } from 'react'

const ContractsPage = () => {
  const { data } = useGetContractsQuery();
  const dispatch = useAppDispatch();

  useEffect(() => {
    if (data) {
      dispatch(setContracts(data))
    }
  },
    [data, dispatch])

  return (
    <>
      <Head>
        <title>Value 😎 based contracts 💊</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`flex flex-col items-center justify-center h-screen ${font.className}`}>
        <NavBar />
        <h1 className="text-6xl font-bold">🫀 Value based contracts</h1>
        <ContractsTable />
      </main>
    </>
  )
}

export default ContractsPage