import React, { useEffect } from 'react'
import { useGetPatientsQuery } from '@/features/patients/api';
import { LoadingSpinner } from '@/components/LoadingSpinner';
import { useAppDispatch } from '@/hooks';
import { PatientsActions } from '@/features/patients/slice';
import PatientsTable from '@/components/PatientsTable';
import Head from 'next/head';
import { NavBar } from '@/components/NavBar';
import { font } from '@/utils/font';


const PatientsPage = () => {
  const { data, isLoading, isSuccess } = useGetPatientsQuery();
  const dispatch = useAppDispatch();

  useEffect(() => {
    if (data) {
      dispatch(PatientsActions.setPatients(data));
    }
  }, [data]);

  return (
    <>
      <Head>
        <title>Value 😎 based contracts 💊</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`flex flex-col items-center justify-center h-screen ${font.className}`}>
        <NavBar />
        <h1 className="text-2xl font-bold pt-10 pb-4">😷 Patients!</h1>
        {isLoading ? (
          <LoadingSpinner />
        ) : (
          <div className='w-3/4 h-3/4'>
            {isSuccess && data && (
              <PatientsTable />
            )
            }
          </div>
        )}
      </main>
    </>
  );
}

export default PatientsPage