import { font } from '@/utils/font'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Value 😎 based contracts 💊</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`flex flex-col items-center justify-center h-screen ${font.className}`}>
        <h1 className="text-6xl font-bold">Value based contracts</h1>
        <p className="text-2xl font-bold">Coming soon</p>
      </main>
    </>
  )
}
